name: slt
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - autopep8=1.5.7=pyhd3eb1b0_0
  - av=8.0.3=py36haea440f_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blosc=1.21.0=h8c45485_0
  - brotli=1.0.9=he6710b0_2
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.4.26=h06a4308_0
  - charls=2.1.0=he6710b0_2
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - cytoolz=0.11.0=py36h7b6447c_0
  - dask-core=2021.3.0=pyhd3eb1b0_0
  - decorator=4.4.2=py_0
  - ffmpeg=4.3.2=hca11adc_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.1.4=h14c3975_1
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - icu=67.1=he1b5a44_0
  - imagecodecs=2020.5.30=py36hfa7d478_2
  - intel-openmp=2022.0.1=h06a4308_3633
  - ipykernel=5.3.4=py36h5ca1d4c_0
  - ipython=7.16.1=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.17.0=py36_0
  - jpeg=9e=h7f8727e_0
  - jupyter_client=6.1.12=pyhd3eb1b0_0
  - jupyter_core=4.7.1=py36h06a4308_0
  - jxrlib=1.1=h7b6447c_2
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libaec=1.0.4=he6710b0_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.1.0=h2733197_1
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.0.1=h8e7db2f_0
  - libzopfli=1.0.3=he6710b0_0
  - lintel=1.0=py36h9b8c89a_1005
  - lz4-c=1.9.3=h295c915_1
  - matplotlib=3.2.2=1
  - matplotlib-base=3.2.2=py36h5fdd944_1
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36he8ac12f_0
  - mkl_fft=1.3.0=py36h54f3939_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.5.1=pyhd3eb1b0_0
  - numpy-base=1.19.2=py36hfa32c7d_0
  - olefile=0.46=py36_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1n=h7f8727e_0
  - parso=0.8.2=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.2.2=py36h06a4308_0
  - prompt-toolkit=3.0.17=pyh06a4308_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycodestyle=2.7.0=pyhd3eb1b0_0
  - pygments=2.9.0=pyhd3eb1b0_0
  - python=3.6.13=h12debd9_1
  - python_abi=3.6=2_cp36m
  - pywavelets=1.1.1=py36h7b6447c_2
  - pyzmq=20.0.0=py36h2531618_1
  - readline=8.1=h27cfd23_0
  - scikit-image=0.17.2=py36hdf5156a_0
  - seaborn=0.11.2=pyhd3eb1b0_0
  - setuptools=52.0.0=py36h06a4308_0
  - snappy=1.1.9=h295c915_0
  - sqlite=3.36.0=hc218d9a_0
  - tifffile=2021.3.17=pyhd3eb1b0_1
  - tk=8.6.10=hbc83047_0
  - toml=0.10.2=pyhd3eb1b0_0
  - toolz=0.11.2=pyhd3eb1b0_0
  - tornado=6.1=py36h27cfd23_0
  - traitlets=4.3.3=py36_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - x264=1!161.3030=h7f98852_1
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==0.9.0
    - adal==1.2.7
    - addict==2.4.0
    - antlr4-python3-runtime==4.8
    - appdirs==1.4.4
    - applicationinsights==0.11.10
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asn1crypto==1.2.0
    - astor==0.8.1
    - astunparse==1.6.3
    - async-generator==1.10
    - attrs==19.3.0
    - awscli==1.22.13
    - backports-tempfile==1.0
    - backports-weakref==1.0.post1
    - beautifulsoup4==4.10.0
    - black==21.4b2
    - bleach==4.1.0
    - botocore==1.23.13
    - cachetools==4.0.0
    - certifi==2019.11.28
    - cffi==1.13.2
    - chardet==3.0.4
    - click==8.0.1
    - colorama==0.4.3
    - contextlib2==0.6.0.post1
    - cryptography==3.4.7
    - cycler==0.10.0
    - databricks-cli==0.15.0
    - dataclasses==0.8
    - defusedxml==0.7.1
    - distro==1.6.0
    - docker==4.4.4
    - docker-pycreds==0.4.0
    - docopt==0.6.2
    - docutils==0.15.2
    - dotnetcore2==2.1.21
    - easydict==1.9
    - entrypoints==0.3
    - et-xmlfile==1.1.0
    - filelock==3.3.1
    - ftfy==6.0.3
    - fusepy==3.0.1
    - future==0.18.2
    - fvcore==0.1.3.post20210317
    - gast==0.3.3
    - gdown==4.4.0
    - gevent==21.12.0
    - gitdb==4.0.7
    - gitpython==3.1.18
    - google-auth==1.10.2
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.1.8
    - greenlet==1.1.2
    - grequests==0.6.0
    - grpcio==1.26.0
    - h5py==2.10.0
    - huggingface-hub==0.0.19
    - hydra-core==1.1.1
    - idna==2.8
    - imageio==2.13.5
    - imageio-ffmpeg==0.4.5
    - importlib-metadata==1.5.0
    - importlib-resources==5.4.0
    - iopath==0.1.9
    - ipywidgets==7.7.0
    - isodate==0.6.0
    - jeepney==0.7.1
    - jinja2==3.0.3
    - jmespath==0.10.0
    - joblib==0.14.1
    - jsonpickle==2.0.0
    - jsonschema==3.2.0
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.1.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - keyboard==0.13.5
    - kiwisolver==1.1.0
    - lmdb==1.2.1
    - markdown==3.1.1
    - markupsafe==2.0.1
    - mistune==0.8.4
    - mlflow-skinny==1.19.0
    - mmcv==1.3.12
    - more-itertools==8.2.0
    - moviepy==1.0.3
    - msal==1.13.0
    - msal-extensions==0.2.2
    - msgpack==1.0.2
    - msrest==0.6.21
    - msrestazure==0.6.4
    - mypy-extensions==0.4.3
    - natsort==7.0.1
    - nbclient==0.5.9
    - nbconvert==6.0.7
    - nbformat==5.1.3
    - ndg-httpsclient==0.5.1
    - nest-asyncio==1.5.4
    - notebook==6.4.8
    - numpy==1.18.1
    - oauthlib==3.1.0
    - omegaconf==2.1.1
    - opencv-python==4.4.0.46
    - openpyxl==3.0.9
    - opt-einsum==3.1.0
    - packaging==21.0
    - pandas==1.0.3
    - pandocfilters==1.5.0
    - pathspec==0.9.0
    - pathtools==0.1.2
    - pillow==8.4.0
    - plotly==4.5.0
    - pluggy==0.13.1
    - portalocker==1.5.2
    - proglog==0.1.9
    - prometheus-client==0.13.1
    - promise==2.3
    - protobuf==3.19.4
    - psutil==5.9.0
    - py==1.8.1
    - pyarrow==3.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.4
    - pycosat==0.6.3
    - pycparser==2.19
    - pydot==1.4.2
    - pygtrie==2.4.2
    - pyjwt==2.1.0
    - pyopenssl==19.1.0
    - pyparsing==2.4.6
    - pyrsistent==0.18.0
    - pysocks==1.7.1
    - pytest==5.4.0
    - python-dateutil==2.8.1
    - pytz==2019.3
    - pyyaml==5.3
    - regex==2021.10.8
    - requests==2.22.0
    - requests-oauthlib==1.3.0
    - retrying==1.3.3
    - rsa==4.0
    - ruamel-yaml==0.15.87
    - s3transfer==0.5.0
    - sacrebleu==1.4.4
    - sacremoses==0.0.46
    - scikit-learn==0.22.2.post1
    - scipy==1.5.4
    - secretstorage==3.3.1
    - send2trash==1.8.0
    - sentencepiece==0.1.90
    - sentry-sdk==1.5.10
    - setproctitle==1.2.3
    - shortuuid==1.0.8
    - simplejson==3.17.3
    - six==1.13.0
    - smmap==4.0.0
    - soupsieve==2.3.1
    - tabulate==0.8.9
    - tensorboard==2.4.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.2.0
    - tensorflow-estimator==2.2.0
    - termcolor==1.1.0
    - terminado==0.12.1
    - testpath==0.5.0
    - timm==0.4.12
    - tokenizers==0.10.3
    - torch==1.9.0
    - torch-tb-profiler==0.2.1
    - torchtext==0.5.0
    - torchvision==0.10.0
    - tqdm==4.40.2
    - transformers==4.11.3
    - typed-ast==1.5.2
    - typing==3.7.4.1
    - typing-extensions==3.10.0.0
    - urllib3==1.25.7
    - wandb==0.12.14
    - warmup-scheduler==0.3
    - wcwidth==0.1.8
    - webencodings==0.5.1
    - websocket-client==1.2.1
    - webvtt-py==0.4.6
    - werkzeug==0.16.0
    - widgetsnbextension==3.6.0
    - wrapt==1.11.2
    - xmltodict==0.12.0
    - yacs==0.1.8
    - yapf==0.31.0
    - zipp==3.1.0
    - zope-event==4.5.0
    - zope-interface==5.4.0
